name: auto-pull-request

on:
  # run manually 
  workflow_dispatch:
  # merge into master|release
  push:
    branches:
      - main

env:
  # required by gh cli
  GH_TOKEN: ${{ github.token }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        branches:
          - team
          - squad

    steps:
      - uses: actions/checkout@v4

      - name: Ensure automated label exists
        run: | 
          gh label create automerge \
            --description "Label for automerge action" \
            --color 0000FF \
            --force

      - name: Check if PR exists
        id: check_pr
        run: |
          pr_exists=$(gh pr list \
            --state open \
            --base ${{ matrix.branches }} \
            --head main)
          echo "pr_exists=$pr_exists" >> $GITHUB_ENV
      
      - name: Raise Pull Request
        if: env.pr_exists == ''
        run: |
          pr_url=$(gh pr create \
            --title "Sync main with ${{ matrix.branches }}" \
            --body "Auto-generated by GitHub Actions" \
            --base ${{ matrix.branches }} \
            --reviewer jjunior-onfleet \
            --label automated \
            --head main)
          echo "pr_url=$pr_url" >> $GITHUB_ENV

      
      - name: Display PR already exists
        if: env.pr_exists != ''
        run: |
          echo "Pull request already exists"

      - name: Run Automerge
        if: env.pr_exists == ''
        id: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          MERGE_ERROR_FAIL: 1
          URL: ${{ env.pr_url }}

      - name: Automerge feedback
        if: steps.automerge.outputs.mergeResult == "merged" && env.pr_exists == ''
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
