name: auto-pull-request

on:
  # run manually 
  workflow_dispatch:
  # merge into master|release
  push:
    branches:
      - main

env:
  # required by gh cli
  GH_TOKEN: ${{ github.token }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        branches:
          - team
          - squad

    steps:
      - uses: actions/checkout@v4

      - name: Ensure automated label exists
        run: | 
          gh label create automated \
            --description "Automated" \
            --color 0000FF \
            --force

      - name: Check if PR exists
        id: check_pr
        run: |
          pr_exists=$(gh pr list \
            --state open \
            --base ${{ matrix.branches }} \
            --head main)
          echo "pr exists value: $pr_exists"
          echo "pr_exists=$pr_exists" >> $GITHUB_ENV
      
      - name: Raise Pull Request
        if: env.pr_exists == ''
        run: |
          gh pr create \
            --title "Sync main with ${{ matrix.branches }}" \
            --body "Auto-generated by GitHub Actions" \
            --base ${{ matrix.branches }} \
            --reviewer jjunior-onfleet \
            --label automated \
            --head main
      
      - name: Display PR already exists
        if: env.pr_exists != ''
        run: |
          echo "Pull request already exists"
