name: auto-merge

on:
  pull_request:
    types:
      - labeled
  workflow_run:
    workflows:
      - auto-pull-request
    types:
      - completed

env:
  # required by gh cli
  GH_TOKEN: ${{ github.token }}

jobs:
  merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Run Automerge
        id: automerge
        if: contains(github.event.pull_request.labels.*.name, 'automerge')
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_ERROR_FAIL: true
