name: auto-pull-request

on:
  # run manually 
  workflow_dispatch:
  # merge into master|release
  push:
    branches:
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        branches:
          - team
          - squad

    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          base: main
          branch: ${{ matrix.branches }}