name: ci

on:
  # require test
  workflow_run:
    workflows: [test]
    types: [completed]
  # run manually 
  workflow_dispatch:
  push:
    paths:
      - ".github/**"
      - "common/**"
  pull_request:
    types:
      - closed
    branches:
      - main
      - squad
    paths:
      - ".github/**"
      - "common/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Build artifact
        run: date
