name: ci

on:
  # run manually 
  workflow_dispatch:
  # merge into master|release
  push:
    branches:
      - main
      - release
    paths:
      - ".github/**"
      - "common/**"
  # PR to designated branches
  pull_request_target:
    types:
      - opened
    branches:
      - squad
    paths:
      - ".github/**"
      - "common/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Build artifact
        run: date
