name: ci

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
      - squad
    paths:
      - ".github/**"
      - "common/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Install npm@8
        run: date
