name: ci

on:
  # run manually 
  workflow_dispatch:
  # merge into master|release
  push:
    branches:
      - release
      - squad
      - team
    paths:
      - ".github/**"
      - "common/**"

env:
  SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set short github.sha
        id: vars
        shell: bash
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV

      - name: print current branch
        id: target_branch
        shell: bash
        run: echo ${{ github.head_ref || github.ref_name }}

      - name: ECS service deployment
        run: |
          if [[ "${{ github.head_ref || github.ref_name }}" == "release" ]] || [[ "${{ github.head_ref || github.ref_name }}" == "main" ]]; then
            echo "master or release deployments currently not allowed. Skipping ECS deployment..."
            exit 0
          else
            echo "aws ecs update-service --cluster ${{ github.head_ref || github.ref_name }} --service ${{ github.head_ref || github.ref_name }}-yerba --force-new-deployment --region us-east-1"
          fi

      - name: Notify deploy
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C064EA5DBFV
          payload: |
            {
              "text": "*Deployment to ${{ github.head_ref || github.ref_name }} ECS cluster started*",
              "attachments": [
                  {
                  "color": "0000FF",
                  "fields": [
                    {
                      "value": ":rocket: Deployed `${{ env.GITHUB_SHA_SHORT }}` to `${{ github.head_ref || github.ref_name }}`",
                      "short": false
                    }
                  ]
                }
              ]
            }
