name: ci

on:
  # run manually 
  workflow_dispatch:
  # merge into master|release
  push:
    branches:
      - main
      - release
    paths:
      - ".github/**"
      - "common/**"
  # PR to designated branches
  pull_request:
    types:
      - closed
    branches:
      - squad
    paths:
      - ".github/**"
      - "common/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set short github.sha
        id: vars
        shell: bash
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)"

      - name: print current branch
        id: target_branch
        shell: bash
        run: echo ${{ github.head_ref || github.ref_name }}
