name: squad-sync
env:
  designated_branch: squad
  slack_channel: C064EA5DBFV

on:
  push:
    branches:
      - main

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: auto-pull-request
        uses: "./.github/workflow-templates/auto-pull-request"
        with:
          branch: "${{ env.designated_branch }}"
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
          slack_channel: "${{ env.slack_channel }}"
          slack_token: "${{ secrets.SLACK_BOT_TOKEN }}"
          pr_base_url: "${{ github.server_url }}/${{ github.repository }}/pull"