name: squad1-sync
env:
  designated_branch: squad1
  slack_channel: C064EA5DBFV

on:
  push:
    branches:
      - main

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Check if branch exists and create if necessary
        shell: bash
        run: |
          if git ls-remote --heads origin refs/heads/"${{ env.designated_branch }}" | grep -q "${{ env.designated_branch }}"; then
            echo "Branch ${{ env.designated_branch }} already exists."
            echo "BRANCH_CREATED=false" >> $GITHUB_ENV
          else
            git checkout -b "${{ env.designated_branch }}"
            git push origin "${{ env.designated_branch }}}"
            echo "BRANCH_CREATED=true" >> $GITHUB_ENV
          fi

      - name: auto-pull-request
        if: ${{ ! env.BRANCH_CREATED }}
        uses: "./.github/workflow-templates/auto-pull-request"
        with:
          branch: "${{ env.designated_branch }}"
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
          slack_channel: "${{ env.slack_channel }}"
          slack_token: "${{ secrets.SLACK_BOT_TOKEN }}"
          pr_base_url: "${{ github.server_url }}/${{ github.repository }}/pull"