name: team-sync
env:
  designated_branch: team
  slack_channel: C064EA5DBFV

on:
  push:
    branches:
      - main

jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: auto-pull-request
        uses: "./.github/workflow-templates/auto-pull-request"
        with:
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
          branch: "${{ env.designated_branch }}"
          slack_channel: ${{ env.slack_channel }}
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
