name: test

on:
  # run manually
  workflow_dispatch:
  # ignore when main|master|release
  push:
    branches-ignore:
      - main
      - master
      - release
    paths:
      - ".github/**"
      - "common/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: date
