name: test

on:
  # run manually
  workflow_dispatch:
  # ignore when main|master|release
  pull_request:
    paths:
      - ".github/**"
      - "common/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set short github.sha
        id: vars
        shell: bash
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)"

      - name: print current branch
        id: target_branch
        shell: bash
        run: echo ${{ github.head_ref || github.ref_name }}


      - name: ECS service deployment
        run: |
          if [[ "${{ github.head_ref || github.ref_name }}" == "release" ]] || [[ "${{ github.head_ref || github.ref_name }}" == "main" ]]; then
            echo "master or release deployments currently not allowed. Skipping ECS deployment..."
            exit 0
          else
            echo "aws ecs update-service --cluster ${{ github.head_ref || github.ref_name }} --service ${{ github.head_ref || github.ref_name }}-yerba --force-new-deployment --region us-east-1"
          fi